#!/bin/sh

[ $# -eq 2 ] || {
    echo "Illegal number of arguments."
    exit 1
}

command -v xargs >/dev/null 2>&1 || {
    echo >&2 "xargs is required. Aborting."
    exit 2
}

fswatch -o `echo $1 | sed -e 's/:/ /g'` | xargs -n1 -I{} $2
