#!/bin/sh

usage() {
    echo "Usage: fswatch-run command path ..."
}

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    usage
    exit 0
fi

[ $# -ge 2 ] || {
    usage
    echo
    echo "Illegal number of arguments."
    exit 1
}

command -v xargs >/dev/null 2>&1 || {
    echo >&2 "xargs is required. Aborting."
    exit 2
}

cmd=$1
shift
fswatch -o $* | xargs -n1 -I{} $cmd
