
name: Release

on: 
  push:
    tags:
    - '*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        include:
            - arch: arm64
            - arch: amd64
    env:
        DOCKER_IMAGE_TAG: fswatch-${{ matrix.arch }}
        DOCKER_CONTAINER_NAME: fswatch-${{ matrix.arch }}
        DOCKER_PLATFORM: linux/${{ matrix.arch }}
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3.0.0
    - name: Build Docker Image
      run: docker build --platform ${DOCKER_PLATFORM} -t ${DOCKER_IMAGE_TAG} .
    - name: Run Container
      run: docker run --name ${DOCKER_CONTAINER_NAME} -d ${DOCKER_IMAGE_TAG}
    - name: Copy Artifacts From Container
      run: |
        docker cp ${DOCKER_CONTAINER_NAME}:/artifacts .
        ls -ltr artifacts
    - name: Release
      uses: ncipollo/release-action@v1.13.0
      with:
        artifacts: "artifacts/*"
        allowUpdates: true
        name: ${{ github.ref_name }}
