
name: Release

on: 
  push:
    tags:
    - '*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4.1.1
    - name: update-pkgs
      run: sudo apt-get -y update
    - name: install-autotools
      run: sudo apt-get install -y git autoconf automake gettext autopoint libtool make g++ texinfo curl
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make -j
    - name: make check
      run: make check
    - name: make install
      run: sudo make install
    - name: Package
      run: |
        mkdir artifacts package && \
        cd package && \
        cp /usr/local/bin/fswatch . && \
        cp -r /usr/local/lib/*fswatch* . && \
        tar -czvf ../artifacts/fswatch-${{ github.ref_name }}.tar.gz . && \
        zip -r ../artifacts/fswatch-${{ github.ref_name }}.zip .
    - name: Release
      uses: ncipollo/release-action@v1.13.0
      with:
        artifacts: "artifacts/*"
        name: ${{ github.ref_name }}
